[alias]
moonbase = " build --release -p moonbeam --no-default-features --features moonbase-native"
moonbase-benchmarks = " build --release -p moonbeam --no-default-features --features moonbase-runtime-benchmarks"
moonbase-betanet = " build --release -p moonbeam --no-default-features --features moonbase-native,betanet-native"
moonbase-tracing = " build --release -p moonbeam --features moonbase-native-tracing"
moonriver = " build --release -p moonbeam --no-default-features --features moonriver-native"
moonriver-betanet = " build --release -p moonbeam --no-default-features --features moonriver-native,betanet-native"
moonriver-axiatest = " build --release -p moonbeam --no-default-features --features moonriver-native,axiatest-native"
moonbeam = " build --release -p moonbeam --no-default-features --features moonbeam-native"
moonbeam-betanet = " build --release -p moonbeam --no-default-features --features moonbeam-native,betanet-native"
